services:
  db:
    image: postgres:15
    container_name: scalper_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: scalper_data
    ports:
      - "5432:5432"
    networks:
      - appnet
  server:
    container_name: server
    build: ./server
    working_dir: /app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    networks:
      - appnet

  api:
      container_name: flask_api
      build: ./api
      working_dir: /app
      depends_on:
        - db
      ports:
        - "5000:5000"
      networks:
        - appnet

  client:
    build: ./client
    working_dir: /app
    depends_on:
      - server
    stdin_open: true
    tty: true
    networks:
      - appnet

networks:
  appnet: